[pkg]
name        = "bingrep"
description = "Greps through binaries from various OSs and architectures"
homepage    = ["https://github.com/m4b/bingrep"]
license     = ["MIT"]
maintainer  = ["QaidVoid (contact@qaidvoid.dev)"]
reason      = "upstream publishes no releases at all, only tags"

[source]
git     = "https://github.com/m4b/bingrep"
commit  = "019d6ed8c2549b30bba2c50763f217d816ccd390"
version = "0.12.1"

[build]
image = "docker.io/library/rust@sha256:b4b54b176a74db7e5c68fdfe6029be39a02ccbcfe72b6e5a3e18e2c61b57ae26"
hosts = ["x86_64-linux", "aarch64-linux"]
deps  = ["musl-dev"]

[build.target]
x86_64-linux  = "x86_64-unknown-linux-musl"
aarch64-linux = "aarch64-unknown-linux-musl"

[build.env]
RUSTFLAGS = "-C target-feature=+crt-static -C link-self-contained=yes"

[build.script]
run = """
rustup target add "$TARGET"
cargo build --release --locked --target "$TARGET"
"""

[artifact]
"target/${target}/release/bingrep" = "bingrep"
"LICENSE"                          = "LICENSE"
