[pkg]
name        = "eza"
description = "A modern replacement for ls"
homepage    = ["https://github.com/eza-community/eza"]
license     = ["MIT"]
maintainer  = ["QaidVoid (contact@qaidvoid.dev)"]

reason = "upstream ships gnu-linked binaries only; soar needs static musl"

[source]
git = "https://github.com/eza-community/eza"
commit  = "98442ab17c2c3738701b62a7e060b1431ae2d6ea"
version = "0.23.5"

[build]
image = "docker.io/library/rust@sha256:b4b54b176a74db7e5c68fdfe6029be39a02ccbcfe72b6e5a3e18e2c61b57ae26"
hosts = ["x86_64-linux", "aarch64-linux"]

deps = ["zlib-dev", "musl-dev"]

[build.target]
x86_64-linux  = "x86_64-unknown-linux-musl"
aarch64-linux = "aarch64-unknown-linux-musl"

[build.env]
RUSTFLAGS = "-C target-feature=+crt-static -C link-self-contained=yes"

[build.script]
run = """
rustup target add "$TARGET"
cargo build --release --locked --target "$TARGET"
"""

[artifact]
"target/${target}/release/eza" = "eza"
"LICENSE.txt"                  = "LICENSE"
